export const STORAGE_KEYS = {
  PEOPLE: 'PEOPLE',
  RELATIONS: 'RELATIONS',
  LANGUAGE: 'LANGUAGE',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  THEME_MODE: 'THEME_MODE',
  IMPORTED_CONTACTS: 'IMPORTED_CONTACTS',
  SUBSCRIPTION_STATUS: 'SUBSCRIPTION_STATUS',
} as const;

